### ISSUE TITLE
what's the problem !!

### ISSUE THREAD

**Issue by bozo4** [1337r00t/SnapBrute#1]
## Enter Usernames File :
> user.txt

## Enter Passwords File :
> pass.txt
Cracking Now !..
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl

**Comment by bozo4** [comment]
and another problem 
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /tools/snapchat/
on this server.</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /tools/snapchat/
on this server.</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
`

**Comment by metakalis** [comment]
how can fux that

**Comment by 1337r00t** [comment]
Fixed Code now #bug 3
