### ISSUE TITLE
Blcock ip 

### ISSUE THREAD

**Issue by l7nbob** [1337r00t/SnapBrute#11]
مازال يعطيني رسالة تبليك ، في حل لهالمشكله ؟

**Comment by gohst121** [comment]
جرب بروكسي يمكن ينفع

**Comment by l7nbob** [comment]
جوبت ال tor service ولا ضبط هل في طريقه ثانيه للبروكسي لاني ماني عارف ادخله على نظام linux

**Comment by gohst121** [comment]
شف اذا دخلت الملف اكتب الامر 
proxychains perl sc.pl 

على الكالي

**Comment by l7nbob** [comment]
بجرب الان و اعطيك خبر

**Comment by l7nbob** [comment]
اعطاني ان ال DNS ما ضبط

**Comment by l7nbob** [comment]
الطلب ما ضبط

**Comment by l7nbob** [comment]
ثم ختمها ب block ip

**Comment by gohst121** [comment]
حتى لو تتخطاه وتغير الاي بي بيبندك من جديد ^.^ مشكلة حاول انك تخمن على حسابه انستا م يعطيك باند 
اسم السكربت 
pulse 
تحصل له شروحات كثير 
باالتوفيق

**Comment by l7nbob** [comment]
اوكي يعطيك العافيه للمعلوميه ال proxychains عندي شغال على ال dynamic ممكن يكون هو السبب ولا ؟
