### ISSUE TITLE
Sorry, your ip [Blocked] .. SnapChat

### ISSUE THREAD

**Issue by mr-ahma** [1337r00t/SnapBrute#12]
السلام عليكم ورحمة والله وبركاته 

لاهنت عندي مشكله وهي حظر الايبي للحين موجود يخمن تقريباً 10 مرات وبعدها حظر ، هل هناك حل ل هالمشكله؟ ومشكور يا بعدي

**Comment by gohst121** [comment]
من الشركة نفسها 
جرب بروكسي
