### ISSUE TITLE
issue using perl

### ISSUE THREAD

**Issue by rootberoyale** [1337r00t/SnapBrute#14]
root@kali:~/Bureau# perl sc.pl
Scalar found where operator expected at sc.pl line 54, near ")
                $code"
        (Missing operator before $code?)
syntax error at sc.pl line 54, near ")
                $code "
Execution of sc.pl aborted due to compilation errors.

**Comment by rootberoyale** [comment]
using ruby

root@kali:~/Bureau# ruby sc.rb
/usr/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (OpenSSL::SSL::SSLError)
        from /usr/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from sc.rb:17:in `block (2 levels) in <main>'
        from sc.rb:7:in `each'
        from sc.rb:7:in `block in <main>'
        from sc.rb:6:in `each'
        from sc.rb:6:in `<main>'
root@kali:~/Bureau#

**Comment by 1337r00t** [comment]
Fixed Perl Script Thx

Ruby script : You can disable SSL check passing an option to net/https for send request .
