### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by metakalis** [1337r00t/SnapBrute#2]
hello  i need help avout script 

i dont know how can use it 

Enter Passwords File :
> pass.txt
Cracking Now !..
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl
Updated Script Go -> https://github.com/1337r00t/SnapBrute/blob/master/brute.pl

can you help me pllz

**Comment by 1337r00t** [comment]
Fixed Code now #bug 2
