### ISSUE TITLE
Outdated code

### ISSUE THREAD

**Issue by InkedCurtis** [1337r00t/SnapBrute#3]
Hey,

It appears the source you've got posted here is outdated but works fine on your site, would you mind updating the source to the latest one on your server please?

**Comment by Deyelk** [comment]
whats his website?

**Comment by InkedCurtis** [comment]
@Deyelk It's located here : http://1337leaks.info/sc/

**Comment by 1337r00t** [comment]
Fixed Code now #bug 1

**Comment by InkedCurtis** [comment]
Hey, is it not possible to get snap stories etc.. anymore?

**Comment by 1337r00t** [comment]
yeah, sure !
`POST https://app.snapchat.com/bq/stories HTTP/1.1
Accept-Language: en;q=0.9
User-Agent: Snapchat/10.3.1.0 (SM-G900F; Android 5.0#G900FXXS1BPCL#21; gzip)
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

req_token=ba47a77e39516b5f935fc2e1fac58b324ac9e67041bbc9d4a60b4b7f2b336a1004kjo=0=fdf`9f2d51b27603222`126j27ee709d0857146699ac18fd7d87c4f10a485efbb1c03f92dc211d891ac47cb108&timestamp=1506282600000&username=ip.d`

**Comment by InkedCurtis** [comment]
@1337r00t you're a star! I'll look and see if this works now!

**Comment by InkedCurtis** [comment]
@1337r00t appears you've changed/disabled your API for Casper, I can't get my account to authenticate anymore
